version: "3.8"

services:
  test_project-php-apache:
    container_name: test_project-php-apache
    build:
      context: ./apache
    ports:
      - ${WEB_PORT}:80
    volumes:
      - ./test_project:/var/www/test_project
    depends_on:
      - test_project-mysql

  test_project-mysql:
    platform: linux/amd64
    container_name: test_project-mysql
    build:
      context: ./mysql
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      - ./mysql/lib:/var/lib/mysql"
      - ./mysql/conf:/etc/mysql
      - ./mysql/logs:/var/log/mysql
      - ./mysql/sql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      TZ: "Asia/Tokyo"
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci